name: bee
recipe: backdrop
config:
  php: 8.2
  webroot: backdrop
  database: mysql
  # Although Drush isn't needed/used, the version that Lando includes by default
  # has a bug that causes all build steps to fail. We therefore need to update
  # Drush to the latest version just to make sure that build steps run properly.
  backdrush: 1.x-1.x
services:
  appserver:
    build:
      # Remove existing symlink for `bee`
      - rm -f /usr/local/bin/bee
      # Make symlink for `bee` pointing to this version.
      - ln -s /app/bee.php /usr/local/bin/bee
      # Download Backdrop.
      - wget -q --show-progress -O /app/backdrop.zip https://github.com/backdrop/backdrop/archive/1.x.zip
      # Download PHPUnit.
      - wget -q --show-progress -O /app/phpunit https://phar.phpunit.de/phpunit-8.5.phar
      - chmod +x /app/phpunit
      # Download Box
      - wget -q --show-progress -O /app/box "https://github.com/box-project/box/releases/download/4.4.0/box.phar"
      - chmod +x /app/box
    run:
      # Run setup tasks.
      - /app/.lando/setup.sh setup
  multisite:
    type: php:8.2
    webroot: multisite
events:
  pre-rebuild:
    # Run clean-up tasks.
    - /app/.lando/setup.sh clean
    # Remove `bee` symlink, Backdrop and PHPUnit.
    - rm -f /usr/local/bin/bee /app/backdrop.zip /app/phpunit /app/box /app/bee.phar
  pre-destroy:
    # Run clean-up tasks.
    - /app/.lando/setup.sh clean
    # Remove `bee` symlink, Backdrop and PHPUnit.
    - rm -f /usr/local/bin/bee /app/backdrop.zip /app/phpunit /app/box /app/bee.phar
tooling:
  bee:
    service: appserver
    cmd: bee
  box:
    service: appserver
    cmd: /app/box
  reset:
    service: appserver
    cmd: /app/.lando/setup.sh
  run-tests:
    service: appserver
    cmd:
      - cd /app/backdrop && /app/phpunit --testsuite backdrop --configuration /app/tests
      - cd /app/multisite && /app/phpunit --testsuite multisite --configuration /app/tests
  # check-code:
  #   service: appserver
  #   cmd: /app/b/vendor/bin/phpcs --standard=/app/b/vendor/backdrop/coder/coder_sniffer/Backdrop --ignore=vendor/* /app/b
proxy:
  appserver:
    - bee.lndo.site
  multisite:
    - multi-1.lndo.site
    - multi-2.lndo.site
    - install-test.lndo.site
