name: Coding standards
on: [pull_request]
jobs:
  phpcs:
    name: Coding standards
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Setup env
        run: echo "REPO_NAME=${PWD##*/}" >> $GITHUB_ENV

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          # No composer, but we need our commandline tool.
          tools: none, phpcs:3.7

      # The checkout action refuses to put it outside, so we have to do it in
      # two steps.
      - name: Get Backdrop conding standard
        uses: actions/checkout@v2
        with:
          repository: backdrop-ops/phpcs
          ref: 1.0.0-beta1
          path: phpcs
      - name: Move standard outside current dir
        run: mv phpcs ..

      - name: Checkout code
        uses: actions/checkout@v2

      # We run phpcs even if phpstan fails.
      - name: Run CodeSniffer
        run: |
          cd ${{ env.REPO_NAME }}
          phpcs --standard=../../phpcs/Backdrop --report=.github/misc/Github.php -n --basepath=. *
