on:
  # Trigger on push or pull request events, but only for the 1.x-1.x branch.
  push:
    branches: [ 1.x-1.x ]
  pull_request:
    branches: [ 1.x-1.x ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # Checks-out repo under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v2

      # Installs and starts Lando.
      - name: Lando
        run: |
          # For downloading latest DEB file, see: https://gist.github.com/gvenzl/1386755861fb42db492276d3864a378c
          # curl -Lo lando.deb $(curl -s https://api.github.com/repos/lando/lando/releases/latest | grep deb | grep https | awk '{ print $2 }' | sed 's/"//g')
          # curl -Lo lando.deb https://github.com/lando/lando/releases/download/v3.11.0/lando-x64-v3.11.0.deb
          # curl -Lo lando.deb https://github.com/lando/lando/releases/download/v3.14.0/lando-x64-v3.14.0.deb
          # curl -Lo lando.deb https://github.com/lando/lando/releases/download/v3.15.0/lando-x64-v3.15.0.deb
          curl -Lo lando.deb https://github.com/lando/lando/releases/download/v3.16.0/lando-x64-v3.16.0.deb
          # curl -Lo lando.deb https://github.com/lando/lando/releases/download/v3.17.0/lando-x64-v3.17.0.deb
          # curl -Lo lando.deb https://github.com/lando/lando/releases/download/v3.17.1/lando-x64-v3.17.1.deb
          # curl -Lo lando.deb https://github.com/lando/lando/releases/download/v3.19.5/lando-x64-v3.19.5.deb
          sudo dpkg -i --ignore-depends=docker-ce lando.deb
          cd $GITHUB_WORKSPACE
          lando start

      # Runs PHPUnit tests.
      - name: PHPUnit
        run: |
          cd $GITHUB_WORKSPACE
          lando run-tests
