on:
  # Trigger on push or pull request events, but only for the 1.x-1.x branch.
  push:
    branches: [ 1.x-1.x, issue-111-update-command ]
  pull_request:
    branches: [ 1.x-1.x, issue-111-update-command ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # Checks-out repo under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3

      # Installs Lando. @see https://docs.lando.dev/install/gha.html
      - name: Lando Setup
        uses: lando/setup-lando@v3
        with:
          lando-version: stable
      # Run Lando
      - name: Lando
        run: |
          cd $GITHUB_WORKSPACE
          lando start

      # Runs PHPUnit tests.
      - name: PHPUnit
        run: |
          cd $GITHUB_WORKSPACE
          lando run-tests
